title: Carl Reimers # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Personal Data Analysis Projects 
  <br><br>
  <a href="https://www.linkedin.com/in/carl-reimers-773590143/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
